name: publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ğŸŸ¢ Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: ğŸ› ï¸ Install & Build
        run: bun install
      - name: ğŸš€ Create Pull Request & Publish
        uses: changesets/action@v1
        with:
          publish: bun changeset publish
          commit: "âœ… chore: update version"
          title: "âœ… chore: update version"
        env:
          LEFTHOOK: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
